services:
  home-library:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
  postgres:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=sanich123
      - POSTGRES_PASSWORD=secret_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 6500:5432
volumes:
  postgres: