version: '3'
services:
  home-library:
    restart: always
    build: .
    ports:
      - '4000:4000'
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    env_file:
      - .env
  postgres:
    image: postgres:15.3
    networks:
      - postgres
    restart: always
    environment: 
      - POSTGRES_USER=sanich123
      - POSTGRES_PASSWORD=secret_password
    volumes:
      - /data/postgres:/data/postgres
    ports:
      - '6500:5432'
    env_file:
      - .env
networks:
  postgres:
    driver: bridge
