version: '3'
services:
  nest-api:
    container_name: nest-api
    restart: always
    build: .
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - postgres
  postgres:
    image: postgres:15.3
    container_name: postgresprisma
    networks:
      - postgres
    restart: always
    environment: 
      - POSTGRES_USER=sanich123
      - POSTGRES_PASSWORD=secret_password
    volumes:
      - /data/postgres:/data/postgres
    ports:
      - 5432:5432
    env_file:
      - .env
networks:
  postgres:
    driver: bridge
